[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
backgroundColor = "#0b0b12"
secondaryBackgroundColor = "#171720"
textColor = "#F2EEE6"
primaryColor = "#F5B731"
font = "sans serif"
